### ISSUE TITLE
Maximum number of stepper motors telemetrix accelstep

### ISSUE THREAD

**Issue by Aminfeky** [MrYsLab/telemetrix#66]
First i would like to thank u for ur amazing work
question is it possible to control more than 4 steppers with accelstep using telemetrix? My project has 7 connected to mega2560 arduino, first 4 works great but cant create more

**Comment by MrYsLab** [comment]
Thanks for the compliment ;-)

The maximum number could be increased from 4 to 8. For Telemetrix4Arduino, the change is simple enough to do. Just change [MAX_NUMBER_OF_STEPPERS](https://github.com/MrYsLab/Telemetrix4Arduino/blob/abc6930aa6f3b0ecffa9700017e0a4ca71cb00de/examples/Telemetrix4Arduino/Telemetrix4Arduino.ino#L681) from 4 to 8. Then, recompile the sketch and upload it.

The Python side is a little more complicated. I created [this branch](https://github.com/MrYsLab/telemetrix/tree/more_steppers) to increase the number of steppers to 8.

Here are the steps you need to do to install this experimental version:

1. In a terminal window, type:
```
pip uninstall telemetrix
```
If you are using a virtual environment, you must execute that command in that environment.

2. Download the **_more_steppers_** version by clicking on the link above and then click the green button to download the repo. If you use a virtual environment, you must move the .zip file there. 
3. Unzip the file. In the directory that contains setup.py, in a terminal window, type:
```
python setup.py
```
Outside of a virtual environment, you may need to use python3 instead of python.

Please let me know if that works. If it does, I will change both telemetrix and Telemetrix4Arduino and release it as the next version.
If it doesn't, please let me know what is happening. 
To return to the previous release, for Telemetrix4Arduino, change the 8 to a 4 and upload it to the Arduino. 
For telemetrix, do a new pip install.

If you need any help with this, please let me know.

**Comment by Aminfeky** [comment]
Works perfectly, thank you so much, people like u make the world a better place

**Comment by MrYsLab** [comment]
Thanks for letting me know. I am going to create releases for these changes. I will let you know when they are available.

**Comment by MrYsLab** [comment]
Telemetrix4Arduino, version 5.3.2,  is now available in the Arduino IDE library manager.
The Python telemetrix package, version 1.35, is available in PyPI. You can install it by using the following command:
```
pip install telemetrix --upgrade
```
I am closing this issue, but please let me know if you have any questions. Please feel free to post here, and I will see it.
